"""Module 8 — Document Forensics (PRD §4.8).

PDF-level red flags collected during ingestion (pdfplumber + the Day-4
`PDFForensics` payload). Each fixture / uploaded AOC-4 carries:

  - pdf_creation_software   string  e.g. 'Adobe LiveCycle Designer', 'Microsoft Word'
  - pdf_metadata_anomaly    bool    True when creation/modification gap < 3 days
  - distinct_fonts          int     (from pdf_parser._extract_forensics)
  - dpi_inconsistency       bool    (image-region scan; Day-11+ extension)

This module compresses those signals into FraudSignal rows. The thresholds and
the suspicious-software list come straight from PRD §4.8.

  | Check                              | Trigger                                       | Severity / +score |
  |------------------------------------|-----------------------------------------------|-------------------|
  | Suspicious creation software       | Word / Excel / Open Office / free PDF tools   | HIGH / +25        |
  | Creation/modification gap < 3 days | pdf_metadata_anomaly == True                   | HIGH / +25        |
  | Font count > 8                     | distinct_fonts > 8 (PRD §4.8 splice marker)    | MEDIUM / +15      |
  | DPI inconsistency in image regions | dpi_inconsistency == True                       | CRITICAL / +40    |

A company that fires any of these gets a `pdf_metadata_anomaly` Boolean flag
written onto its FinancialStatement (so downstream scoring sees it without
re-running the parser). Day-11 acceptance line (PRD §10): 'Document forensics
fires anomaly flag.'
"""

from __future__ import annotations

from dataclasses import dataclass

from backend.app.ingest.schemas import RawFinancialStatement
from backend.app.modules.base import (
    FraudSignal,
    ModuleResult,
    Severity,
    clamp_score,
)

MODULE_NAME = "m08_document_forensics"

# Audit reports are conventionally produced via professional desktop publishing
# (InDesign, LiveCycle, Acrobat Pro). When the PDF was generated by a general
# office tool, the production chain is suspicious — PRD §4.8 verbatim list.
SUSPICIOUS_CREATION_SOFTWARE: tuple[str, ...] = (
    "microsoft word",
    "ms word",
    "winword",
    "microsoft excel",
    "ms excel",
    "libreoffice",
    "openoffice",
    "open office",
    "wps office",
    "tinypdf",
    "smallpdf",
    "pdfescape",
    "scanned",   # ScanSnap / generic scan-to-PDF utilities
)

# PRD §4.8 thresholds
FONT_COUNT_RED_FLAG = 8
CREATION_MOD_GAP_FLOOR_DAYS = 3


@dataclass(frozen=True)
class ForensicInputs:
    """All the per-FS signals the module needs in one struct so the caller
    can hydrate from either fixture data or live pdfplumber output."""

    fs: RawFinancialStatement
    distinct_fonts: int = 0
    dpi_inconsistency: bool = False
    creation_mod_gap_days: int | None = None  # None = unknown / not extracted


def _is_suspicious_software(software: str | None) -> bool:
    if not software:
        return False
    low = software.lower()
    return any(token in low for token in SUSPICIOUS_CREATION_SOFTWARE)


def _check_creation_software(inputs: ForensicInputs) -> FraudSignal | None:
    if not _is_suspicious_software(inputs.fs.pdf_creation_software):
        return None
    return FraudSignal(
        signal_type="DOC_FORENSICS_SUSPICIOUS_CREATOR",
        severity=Severity.HIGH,
        score_contribution=25.0,
        evidence_string=(
            f"AOC-4 PDF created by '{inputs.fs.pdf_creation_software}' — "
            f"general office software, not a professional audit production tool. "
            f"PRD §4.8 fabrication marker."
        ),
        module_name=MODULE_NAME,
        triggered_by=[{"label": "FinancialStatement", "cin": inputs.fs.cin, "year": inputs.fs.year}],
    )


def _check_creation_mod_gap(inputs: ForensicInputs) -> FraudSignal | None:
    """Either the explicit pdf_metadata_anomaly bool OR the computed gap fires."""
    fired = inputs.fs.pdf_metadata_anomaly
    detail = "pdf_metadata_anomaly=True on stored FinancialStatement"
    if not fired and inputs.creation_mod_gap_days is not None:
        if inputs.creation_mod_gap_days < CREATION_MOD_GAP_FLOOR_DAYS:
            fired = True
            detail = (
                f"creation_mod_gap_days = {inputs.creation_mod_gap_days} "
                f"(< {CREATION_MOD_GAP_FLOOR_DAYS}-day floor)"
            )
    if not fired:
        return None
    return FraudSignal(
        signal_type="DOC_FORENSICS_METADATA_GAP",
        severity=Severity.HIGH,
        score_contribution=25.0,
        evidence_string=(
            f"PDF creation / modification window is implausibly tight — {detail}. "
            f"Legitimate AOC-4 filings show a >3-day audit-then-sign gap."
        ),
        module_name=MODULE_NAME,
        triggered_by=[{"label": "FinancialStatement", "cin": inputs.fs.cin, "year": inputs.fs.year}],
    )


def _check_font_count(inputs: ForensicInputs) -> FraudSignal | None:
    if inputs.distinct_fonts <= FONT_COUNT_RED_FLAG:
        return None
    return FraudSignal(
        signal_type="DOC_FORENSICS_FONT_COUNT_HIGH",
        severity=Severity.MEDIUM,
        score_contribution=15.0,
        evidence_string=(
            f"AOC-4 PDF uses {inputs.distinct_fonts} distinct fonts "
            f"(> {FONT_COUNT_RED_FLAG} threshold). Excessive font variety is "
            f"a copy/paste-splice marker per PRD §4.8."
        ),
        module_name=MODULE_NAME,
        triggered_by=[{"label": "FinancialStatement", "cin": inputs.fs.cin, "year": inputs.fs.year}],
    )


def _check_dpi_inconsistency(inputs: ForensicInputs) -> FraudSignal | None:
    if not inputs.dpi_inconsistency:
        return None
    return FraudSignal(
        signal_type="DOC_FORENSICS_DPI_INCONSISTENT",
        severity=Severity.CRITICAL,
        score_contribution=40.0,
        evidence_string=(
            f"Image regions inside AOC-4 PDF show inconsistent DPI — "
            f"indicates inserted screenshots or photo-pasted tables. "
            f"PRD §4.8 CRITICAL fabrication marker."
        ),
        module_name=MODULE_NAME,
        triggered_by=[{"label": "FinancialStatement", "cin": inputs.fs.cin, "year": inputs.fs.year}],
    )


def run(inputs_list: list[ForensicInputs]) -> ModuleResult:
    """Score every FinancialStatement's forensic profile. Returns aggregate
    severity for the company across all years on file."""
    if not inputs_list:
        return ModuleResult.skipped_for(MODULE_NAME, "", None, "No FS forensic inputs")

    cin = inputs_list[0].fs.cin
    latest_year = max(i.fs.year for i in inputs_list)

    signals: list[FraudSignal] = []
    for inputs in inputs_list:
        for sig in (
            _check_creation_software(inputs),
            _check_creation_mod_gap(inputs),
            _check_font_count(inputs),
            _check_dpi_inconsistency(inputs),
        ):
            if sig is not None:
                signals.append(sig)

    return ModuleResult(
        module_name=MODULE_NAME,
        cin=cin,
        year=latest_year,
        score=clamp_score(sum(s.score_contribution for s in signals)),
        signals=signals,
    )


def run_for_fs_list(fs_list: list[RawFinancialStatement]) -> ModuleResult:
    """Convenience wrapper that builds ForensicInputs straight off the FS list."""
    return run([ForensicInputs(fs=fs) for fs in fs_list])
